# AppVeyor build configuration
# https://www.appveyor.com/docs/build-configuration
# https://www.appveyor.com/docs/appveyor-yml/
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.1.0.0.7.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017
# Enable Windows RDP Client Access to Build Worker
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#---------------------------------#
#       build configuration       #
#---------------------------------#

# add several platforms to build matrix:
platform:
  - x64
#  - ARM
#  - Win32
# add several configurations to build matrix:
configuration:
  - Release
#  - Debug
#  - AnalysisRelease
matrix:
  allow_failures:
    - platform: ARM
    - platform: Win32
    - configuration: AnalysisRelease
    - configuration: Debug

# scripts to run before build
before_build:

# use custom build_script
build_script:
# yaml syntax for multiple lines with multiple statements
- |- 
    ECHO BUILD %CONFIGURATION% %PLATFORM%
    set SRC=%APPVEYOR_BUILD_FOLDER%
    ECHO %SRC%
    set BUILDTREE=%SRC%\build-win\
    ECHO %BUILDTREE%
    SET cmake_platform="Visual Studio 15 2017 Win64"
    REM # create Build Tree #
    mkdir %BUILDTREE%
    mkdir %BUILDTREE%\deps
    REM # Change to Build Tree directory #
    cd %BUILDTREE%
    REM # packages from nuget #
    cd %BUILDTREE%\deps
    SET VER=1.2.11.8899
    set ZLIBDIR=%BUILDTREE%\deps\zlib-msvc-%PLATFORM%.%VER%\build\native
    nuget install zlib-msvc-%PLATFORM% -Version %VER%
    SET VER=1.3.4.8788
    set FLTKDIR=%BUILDTREE%\deps\FLTK-msvc-%PLATFORM%.%VER%\build\native
    nuget install FLTK-msvc-%PLATFORM% -Version %VER%
    mkdir %BUILDTREE%\OpenEXR
    cd %BUILDTREE%\OpenEXR
    REM
# yaml syntax for multiple lines with one statement
- cmd: "
cmake -G %cmake_platform% ^
-DBUILD_ILMBASE_STATIC:BOOL=ON ^
-DOPENEXR_BUILD_ILMBASE:BOOL=ON ^
-DOPENEXR_BUILD_OPENEXR:BOOL=ON ^
-DOPENEXR_BUILD_PYTHON_LIBS:BOOL=OFF ^
-DOPENEXR_BUILD_VIEWERS:BOOL=ON ^
-DOPENEXR_BUILD_TESTS:BOOL=ON ^
-DOPENEXR_RUN_FUZZ_TESTS:BOOL=OFF ^
-DOPENEXR_BUILD_UTILS:BOOL=ON ^
-DOPENEXR_BUILD_SHARED:BOOL=OFF ^
-DOPENEXR_BUILD_STATIC:BOOL=ON ^
-DBUILD_SHARED_LIBS:BOOL=OFF ^
-DCMAKE_CONFIGURATION_TYPES:STRING=Debug;Release; ^
-DCMAKE_CXX_FLAGS_RELEASE='/MD' ^
-DCMAKE_CXX_FLAGS_DEBUG='/MDd' ^
-DCMAKE_C_FLAGS_RELEASE='/MD' ^
-DCMAKE_C_FLAGS_DEBUG='/MDd' ^
-DZLIB_LIBRARY=%ZLIBDIR%/lib_release/zlibstatic.lib ^
-DZLIB_INCLUDE_DIR=%ZLIBDIR%/include ^
-DFLTK_BASE_LIBRARY_RELEASE=%FLTKDIR%/lib_release/fltk.lib ^
-DFLTK_GL_LIBRARY_RELEASE=%FLTKDIR%/lib_release/fltk_gl.lib ^
-DFLTK_FORMS_LIBRARY_RELEASE=%FLTKDIR%/lib_release/fltk_forms.lib ^
-DFLTK_IMAGES_LIBRARY_RELEASE=%FLTKDIR%/lib_release/fltk_images.lib ^
-DFLTK_BASE_LIBRARY_DEBUG=%FLTKDIR%/lib_debug/fltkd.lib ^
-DFLTK_GL_LIBRARY_DEBUG=%FLTKDIR%/lib_debug/fltk_gld.lib ^
-DFLTK_FORMS_LIBRARY_DEBUG=%FLTKDIR%/lib_debug/fltk_formsd.lib ^
-DFLTK_IMAGES_LIBRARY_DEBUG=%FLTKDIR%/lib_debug/fltk_imagesd.lib ^
-DFLTK_INCLUDE_DIR=%FLTKDIR%/include ^
-DCMAKE_INSTALL_PREFIX=%BINDIR% ^
-DCMAKE_BUILD_TYPE='Release' %SRC%
"
# statements to pipe warnings to appveyor web gui
- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- set MSBuildOptions=/v:m /m /p:BuildInParallel=true /p:Configuration=%CONFIGURATION% /logger:%MSBuildLogger% /p:RunCodeAnalysis=true
- msbuild %MSBuildOptions% OpenEXRMetaProject.sln

# scripts to run after build
after_build:
  # zip the build archive
  - tree /F %BUILDTREE%\OpenEXR\bin
  - tree /F %BUILDTREE%\OpenEXR
  - 7z a %APPVEYOR_BUILD_FOLDER%\OpenEXR-%CONFIGURATION%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%.zip %BUILDTREE%\OpenEXR\bin

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#specify artifacts to upload
artifacts:
  - path: OpenEXR-%CONFIGURATION%-%PLATFORM%-%APPVEYOR_REPO_COMMIT%.zip
    name: OpenEXR-%CONFIGURATION%-%PLATFORM%

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# to disable deployment
deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  - ECHO "BUILD VICTORY"

# on build failure
on_failure:
  - ECHO "TRY AND TRY AGAIN"

# after build failure or success
on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# https://www.appveyor.com/docs/environment-variables/
# Environment variables that are set by AppVeyor for every build:
# APPVEYOR - True if build runs in AppVeyor environment;
  - ECHO %APPVEYOR%
# CI - True if build runs in AppVeyor environment;
  - ECHO %CI%
# APPVEYOR_API_URL - AppVeyor Build Agent API URL;
  - ECHO %APPVEYOR_API_URL%
# APPVEYOR_ACCOUNT_NAME - account name;
  - ECHO %APPVEYOR_ACCOUNT_NAME%
# APPVEYOR_PROJECT_ID - AppVeyor unique project ID;
  - ECHO %APPVEYOR_PROJECT_ID%
# APPVEYOR_PROJECT_NAME - project name;
  - ECHO %APPVEYOR_PROJECT_NAME%
# APPVEYOR_PROJECT_SLUG - project slug (as seen in project details URL);
  - ECHO %APPVEYOR_PROJECT_SLUG%
# APPVEYOR_BUILD_FOLDER - path to clone directory;
  - ECHO %APPVEYOR_BUILD_FOLDER%
# APPVEYOR_BUILD_ID - AppVeyor unique build ID;
  - ECHO %APPVEYOR_BUILD_ID%
# APPVEYOR_BUILD_NUMBER - build number;
  - ECHO %APPVEYOR_BUILD_NUMBER%
# APPVEYOR_BUILD_VERSION - build version;
  - ECHO %APPVEYOR_BUILD_VERSION%
# APPVEYOR_PULL_REQUEST_NUMBER - GitHub Pull Request number;
  - ECHO %APPVEYOR_PULL_REQUEST_NUMBER%
# APPVEYOR_PULL_REQUEST_TITLE - GitHub Pull Request title
  - ECHO %APPVEYOR_PULL_REQUEST_TITLE%
# APPVEYOR_JOB_ID - AppVeyor unique job ID;
  - ECHO %APPVEYOR_JOB_ID%
# APPVEYOR_JOB_NAME - job name;
  - ECHO %APPVEYOR_JOB_NAME%
# APPVEYOR_REPO_PROVIDER - github, bitbucket, kiln, vso or gitlab;
  - ECHO %APPVEYOR_REPO_PROVIDER%
# APPVEYOR_REPO_SCM - git or mercurial;
  - ECHO %APPVEYOR_REPO_SCM%
# APPVEYOR_REPO_NAME - repository name in format owner-name/repo-name;
  - ECHO %APPVEYOR_REPO_NAME%
# APPVEYOR_REPO_BRANCH - build branch. For Pull Request commits it is base branch PR is merging into;
  - ECHO %APPVEYOR_REPO_BRANCH%
# APPVEYOR_REPO_TAG - true if build has started by pushed tag; otherwise false;
  - ECHO %APPVEYOR_REPO_TAG%
# APPVEYOR_REPO_TAG_NAME - contains tag name for builds started by tag; otherwise this variable is undefined;
  - ECHO %APPVEYOR_REPO_TAG_NAME%
# APPVEYOR_REPO_COMMIT - commit ID (SHA);
  - ECHO %APPVEYOR_REPO_COMMIT%
# APPVEYOR_REPO_COMMIT_AUTHOR - commit author’s name;
  - ECHO %APPVEYOR_REPO_COMMIT_AUTHOR%
# APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL - commit author’s email address;
  - ECHO %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%
# APPVEYOR_REPO_COMMIT_TIMESTAMP - commit date/time;
  - ECHO %APPVEYOR_REPO_COMMIT_TIMESTAMP%
#
# commit message disabled; can cause false failure
#
# APPVEYOR_REPO_COMMIT_MESSAGE - commit message;
#  - ECHO %APPVEYOR_REPO_COMMIT_MESSAGE%
# APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED - the rest of commit message after line break (if exists);
#  - ECHO %APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%
# APPVEYOR_SCHEDULED_BUILD - True if the build runs by scheduler;
  - ECHO %APPVEYOR_SCHEDULED_BUILD%
# APPVEYOR_FORCED_BUILD (True or undefined) - builds started by “New build” button or from the same API;
  - ECHO %APPVEYOR_FORCED_BUILD%
# APPVEYOR_RE_BUILD (True or undefined) - build started by “Re-build commit/PR” button of from the same API;
  - ECHO %APPVEYOR_RE_BUILD%
# PLATFORM - platform name set on Build tab of project settings (or through platform parameter in appveyor.yml);
  - ECHO %PLATFORM%
# CONFIGURATION - configuration name set on Build tab of project settings (or through configuration parameter in appveyor.yml);
  - ECHO %CONFIGURATION%

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Email
    to:
      - RobertPancoast77@gmail.com


