# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - imagemagick # for convert, for test images
    - openexr     # for exrheader, for test images
  jobs:
    pre_build:
       - python docs/scripts/test_images.py 
       
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
