#-*-cmake-*-
#
# This auxiliary CMake file helps in find the ILMBASE headers and libraries
#
# ILMBASE2_FOUND                  set if ILMBASE is found.
# ILMBASE2_INCLUDE_DIR            ILMBASE's include directory
# Ilmbase2_HALF_LIBRARY           ILMBASE's Half libraries
# Ilmbase2_IEX_LIBRARY            ILMBASE's Iex libraries
# Ilmbase2_IEXMATH_LIBRARY        ILMBASE's Iex libraries
# Ilmbase2_ILMTHREAD_LIBRARY      ILMBASE's IlmThread libraries
# Ilmbase2_IMATH_LIBRARY          ILMBASE's Imath libraries

FIND_PATH ( ILMBASE2_LOCATION include/OpenEXR/IlmBaseConfig.h
  PATHS ${ILMBASE_PACKAGE_PREFIX} ENV ${ILMBASE2_ROOT}
  NO_DEFAULT_PATH
  NO_SYSTEM_ENVIRONMENT_PATH
  )

MESSAGE ( "ILMBASE2_LOCATION = ${ILMBASE2_LOCATION}")

MACRO ( FIND_LIBRARY_EX OUTPUT_VAR LIBRARY_NAME LIBRARY_PATHS LIBRARY_SUFFIX )
  SET ( ORIGINAL_CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES} )

  SET(CMAKE_FIND_LIBRARY_SUFFIXES ${LIBRARY_SUFFIX})
  FIND_LIBRARY ( ${OUTPUT_VAR} ${LIBRARY_NAME}
    PATHS ${LIBRARY_PATHS}
    NO_DEFAULT_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    )

  SET ( CMAKE_FIND_LIBRARY_SUFFIXES ${ORIGINAL_CMAKE_FIND_LIBRARY_SUFFIXES} )
ENDMACRO ()

IF ( ILMBASE2_LOCATION )
  
  MESSAGE ( STATUS "Found Ilmbase2 " ${ILMBASE2_LOCATION} )
  SET ( ILMBASE2_INCLUDE_DIRS
    ${ILMBASE2_LOCATION}/include
    ${ILMBASE2_LOCATION}/include/OpenEXR
    CACHE STRING "Ilmbase2 include directories")
  SET ( ILMBASE2_LIBRARY_DIRS ${ILMBASE2_LOCATION}/lib
    CACHE STRING "Ilmbase2 library directories")
  SET ( ILMBASE2_FOUND TRUE )
  
  IF (Ilmbase2_USE_STATIC_LIBS)
    IF (WIN32)
      FIND_LIBRARY_EX ( Ilmbase2_HALF_LIBRARY Half ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IEX_LIBRARY Iex-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IEXMATH_LIBRARY IexMath-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IMATH_LIBRARY Imath-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
    ELSE (WIN32)
      FIND_LIBRARY_EX ( Ilmbase2_HALF_LIBRARY Half ${ILMBASE2_LOCATION}/lib ".a")
      FIND_LIBRARY_EX ( Ilmbase2_IEX_LIBRARY Iex-2_1 ${ILMBASE2_LOCATION}/lib ".a")
      FIND_LIBRARY_EX ( Ilmbase2_IEXMATH_LIBRARY IexMath-2_1 ${ILMBASE2_LOCATION}/lib ".a")
      FIND_LIBRARY_EX ( Ilmbase2_IMATH_LIBRARY Imath-2_1 ${ILMBASE2_LOCATION}/lib ".a")
    ENDIF(WIN32)
  ELSE (Ilmbase2_USE_STATIC_LIBS)
    IF (WIN32)
      FIND_LIBRARY_EX ( Ilmbase2_HALF_LIBRARY Half ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IEX_LIBRARY Iex-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IEXMATH_LIBRARY IexMath-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
      FIND_LIBRARY_EX ( Ilmbase2_IMATH_LIBRARY Imath-2_1 ${ILMBASE2_LOCATION}/lib ".lib")
    ELSEIF (APPLE)
      FIND_LIBRARY_EX ( Ilmbase2_HALF_LIBRARY Half ${ILMBASE2_LOCATION}/lib ".dylib")
      FIND_LIBRARY_EX ( Ilmbase2_IEX_LIBRARY Iex-2_1 ${ILMBASE2_LOCATION}/lib ".dylib")
      FIND_LIBRARY_EX ( Ilmbase2_IEXMATH_LIBRARY IexMath-2_1 ${ILMBASE2_LOCATION}/lib ".dylib")
      FIND_LIBRARY_EX ( Ilmbase2_IMATH_LIBRARY Imath-2_1 ${ILMBASE2_LOCATION}/lib ".dylib")
    ELSE (WIN32)
      FIND_LIBRARY_EX ( Ilmbase2_HALF_LIBRARY Half ${ILMBASE2_LOCATION}/lib ".so")
      FIND_LIBRARY_EX ( Ilmbase2_IEX_LIBRARY Iex-2_1 ${ILMBASE2_LOCATION}/lib ".so")
      FIND_LIBRARY_EX ( Ilmbase2_IEXMATH_LIBRARY IexMath-2_1 ${ILMBASE2_LOCATION}/lib ".so")
      FIND_LIBRARY_EX ( Ilmbase2_IMATH_LIBRARY Imath-2_1 ${ILMBASE2_LOCATION}/lib ".so")
    ENDIF(WIN32)
  ENDIF ()

ENDIF ( ILMBASE2_LOCATION )
