version: 2
jobs:
  build:
    docker:
      - image: aloysbaillet/aswf-vfx2018-conan

    steps:
      - checkout

      - restore_cache:
          key: OpenEXR-conan-data-cache-vfx2018
          paths:
            - /home/circleci/.conan/data

      - run:
          name: prepare build folder
          command: |
            mkdir build

      - run:
          name: OpenEXR build
          working_directory: build
          command: |
            conan install .circleci/
            source activate_run.sh
            cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
            make -j 4

      - run:
          name: OpenEXR tests
          working_directory: build
          no_output_timeout: 20m
          command: |
            source activate_run.sh
            ctest -vv -E PyImathNumpyTest --no-compress-output -T Test

      - store_test_results:
          path: build/Testing

      - save_cache:
          key: OpenEXR-conan-data-cache-vfx2018
          paths:
            - /home/circleci/.conan/data
