version: 2
jobs:
  build:
    docker:
      - image: aloysbaillet/aswf-vfx2018-conan

    steps:
      - checkout

      - restore_cache:
          key: conan-data-cache
          paths:
            - /home/circleci/.conan/data

      - run:
          name: prepare build folder
          command: |
            mkdir build

      - run:
          name: OpenEXR build
          working_directory: build
          command: |
            conan install ..
            cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
            make -j 4

      - run:
          name: OpenEXR tests
          working_directory: build
          command: |
            ctest -vv -E PyImathNumpyTest

      - save_cache:
          key: conan-data-cache
          paths:
            - /home/circleci/.conan/data
