// SPDX-License-Identifier: BSD-3-Clause
// Copyright Contributors to the OpenEXR Project.

// This file is auto-generated by the configure step

#ifndef INCLUDED_OPENEXR_CONFIG_H
#define INCLUDED_OPENEXR_CONFIG_H 1

#pragma once

//
// Current internal library namepace name
//
#undef OPENEXR_IMF_INTERNAL_NAMESPACE_CUSTOM
#undef OPENEXR_IMF_INTERNAL_NAMESPACE

//
// Current public user namepace name
//

#undef OPENEXR_IMF_NAMESPACE_CUSTOM
#undef OPENEXR_IMF_NAMESPACE

//
// Version string for runtime access
//

#undef OPENEXR_VERSION_STRING
#undef OPENEXR_PACKAGE_STRING

#undef OPENEXR_VERSION_MAJOR
#undef OPENEXR_VERSION_MINOR
#undef OPENEXR_VERSION_PATCH

// Version as a single hex number, e.g. 0x01000300 == 1.0.3
#define OPENEXR_VERSION_HEX ((uint32_t(OPENEXR_VERSION_MAJOR) << 24) | \
                             (uint32_t(OPENEXR_VERSION_MINOR) << 16) | \
                             (uint32_t(OPENEXR_VERSION_PATCH) <<  8))

#endif // INCLUDED_OPENEXR_CONFIG_H
