# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenEXR Project.

set(ILMBASE_VERSION_MAJOR 2)
set(ILMBASE_VERSION_MINOR 5)
set(ILMBASE_VERSION_PATCH 2)
set(ILMBASE_VERSION       ${ILMBASE_VERSION_MAJOR}.${ILMBASE_VERSION_MINOR}.${ILMBASE_VERSION_PATCH})
set(ILMBASE_VERSION_API   ${ILMBASE_VERSION_MAJOR}_${ILMBASE_VERSION_MINOR})
set(ILMBASE_SOCURRENT 25)
set(ILMBASE_SOREVISION 1)
set(ILMBASE_SOAGE 0)
math(EXPR ILMBASE_SOVERSION "${ILMBASE_SOCURRENT} - ${ILMBASE_SOAGE}")
set(ILMBASE_LIB_VERSION "${ILMBASE_SOVERSION}.${ILMBASE_SOAGE}.${ILMBASE_SOREVISION}")
message(STATUS "Configure ILMBASE Version: ${ILMBASE_VERSION} Lib API: ${ILMBASE_LIB_VERSION}")
unset(CONFIGURE_AC_CONTENTS)
